management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS

spring:
  security:
    user:
      name: admin
      password: admin

eureka:
  instance:
    metadata-map:
      # needed for Spring Boot Admin to register the service
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

security:
  jwt:
    token:
      secret: s3cr3t
      expires-in: 3600000

