server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://manager:manager@localhost:8761/eureka/

  instance:
    metadata-map:
      # see DiscoveryClientConfigServiceBootstrapConfiguration#refresh
      user: ${spring.security.user.name}
      password: ${spring.security.user.password}
